name: Spring Boot CI/CD

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: 코드 체크아웃
        uses: actions/checkout@v2

      - name: JDK 설치
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: application.properties 생성
        run: |
          mkdir -p src/main/resources
          cat <<EOF > src/main/resources/application.properties
          spring.application.name=${{ secrets.SPRING_APPLICATION_NAME }}
          server.port=${{ secrets.SERVER_PORT }}
          
          spring.datasource.url=${{ secrets.SPRING_DATASOURCE_URL }}
          spring.datasource.username=${{ secrets.SPRING_DATASOURCE_USERNAME }}
          spring.datasource.password=${{ secrets.SPRING_DATASOURCE_PASSWORD }}
          
          spring.jpa.hibernate.ddl-auto=${{ secrets.SPRING_JPA_DDL_AUTO }}
          spring.jpa.show-sql=${{ secrets.SPRING_JPA_SHOW_SQL }}
          spring.jpa.properties.hibernate.format_sql=${{ secrets.SPRING_JPA_FORMAT_SQL }}
          
          logging.level.org.hibernate.SQL=${{ secrets.LOGGING_SQL_LEVEL }}
          EOF

      - name: Gradle 빌드
        run: ./gradlew build
